#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-autosync-clear() {
    declare desc="Clears the autosync deploy key for this app"
    declare cmd="autosync"
    # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##
    declare APP="$2"

    [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

    local APP_PATH=$DOKKU_ROOT/$APP

    if [[ -f "$APP_PATH/deploy" ]]; then
        rm "$APP_PATH/deploy"
    fi
    if [[ -f "$APP_PATH/deploy.pub" ]]; then
        rm "$APP_PATH/deploy.pub"
    fi
    if [[ -f "$APP_PATH/autosync" ]]; then
        rm "$APP_PATH/autosync"
    fi    
    echo "autosync configuration as been cleared"
}

cmd-autosync-clear "$@"
