#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

cmd-autosync-default() {
    declare APP="$2"
    declare REPO="${3}"
    declare TAGNAME="${4:-main}"
    declare GITUSER="git"
    declare desc="Updates the app from a remote git repo"
    declare cmd="autosync"

    # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"                                                                                                                                                                                                                   
    local argv=("$@")

    echo $argv
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##

    APP="$2"
    REPO="${3}"

    [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
    verify_app_name "$APP"

    eval "$(config_export global)"
    eval "$(config_export app "$APP")"

    local repo="$DOKKU_AUTOSYNC_REPO"
    REPO="${3:-${repo}}"

    if [ "${REPO}" == "" ] ; then
        dokku_log_warn "ERROR: Cannot complete autosync without a repository name!"
        dokku_log_warn "  please provide your default repository using"
        dokku_log_warn "  dokku config:set --no-restart $app DOKKU_AUTOSYNC_REPO=<repository name>"
        return 1
    fi
    
    DEFAULT_BRANCH="$(fn-plugin-property-get "git" "$APP" "deploy-branch" "master")"
    TAGNAME="${4:-${DEFAULT_BRANCH}}"

    local APP_PATH=$DOKKU_ROOT/$APP

    cd "$APP_PATH"
    git fetch "$GITUSER@${APP}:${REPO}" "$TAGNAME"
}

cmd-autosync-default "$@"
