#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-autosync-key() {
    declare desc="Outputs the autosync deploy key for this app"
    declare cmd="autosync"
    [[ "$1" == "$cmd" ]] && shift 1
    
    declare APP="$1"

    [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

    local APP_PATH=$DOKKU_ROOT/$APP
    if [[ ! -f "$APP_PATH/deploy.pub" ]]; then
        dokku_log_fail "There is no deploy key, please setup the autosync plugin"
    fi
    cat "$APP_PATH/deploy.pub"
}

cmd-autosync-key "$@"
