#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

cmd-autosync-setup() {
    declare desc="Creates the autosync deploy key for this app"
    declare cmd="autosync"
 
    # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##
    declare APP="$2"
    declare HOST="github.com"
    
    [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

    eval "$(config_export global)"
    eval "$(config_export app "$APP")"

    local email="$DOKKU_AUTOSYNC_EMAIL"

    # check we have a valid e-mail address
    if [ -z "$email" ]; then
        dokku_log_warn "ERROR: Cannot configure autosync without an email address!"
        dokku_log_warn "  please provide your e-mail address using"
        dokku_log_warn "  dokku config:set --no-restart $app DOKKU_AUTOSYNC_EMAIL=<e-mail>"
        return 1
    fi

    # allow the hostname to be overridden
    local host="$DOKKU_AUTOSYNC_HOST"
    if [[ "${host}" != "" ]]; then
        HOST="${host}"
    fi
    
    local APP_PATH=$DOKKU_ROOT/$APP
    if [[ -f "$APP_PATH/deploy.pub" ]]; then
        dokku_log_fail "There is already a deploy key, please clear the autosync plugin if you need to change your settings"
    fi

    # create the key
    ssh-keygen -t ed25519 -C "${email}" -f "$APP_PATH/deploy" -q -N ""
    cat "$APP_PATH/deploy.pub"

    # create the ssh config file
    echo -e "Host ${APP}\n\tHostname ${HOST}\n\tIdentityFile ~/${APP}/deploy\n\tIdentitiesOnly yes\n" > "$APP_PATH/autosync"
    chmod 644 "$APP_PATH/autosync"
}

cmd-autosync-setup "$@"
